apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-1yon
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-1yon@sha256:44f8f454ac97019589b1860d1d37489186b24a727cba54abd332b9a09fdec617
        name: my-nodejs
        resources: {}
status: {}
